# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,10,2])
a1
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[2,10,15],[14,18,22]])
a2.shape
# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[10,5,4,3],
              [12,6,5,9],
              [12,3,6,5]],
             
             [[2,6,7,5],
             [3,15,45,6],
             [22,4,3,8]],])
a3

array([[[10,  5,  4,  3],
        [12,  6,  5,  9],
        [12,  3,  6,  5]],

       [[ 2,  6,  7,  5],
        [ 3, 15, 45,  6],
        [22,  4,  3,  8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.size,a1.ndim,a1.dtype

((3,), 3, 1, dtype('int32'))

In [4]:
# Attributes of 2-dimensional array
a2.shape,a2.size,a2.ndim,a2.dtype

((2, 3), 6, 2, dtype('int32'))

In [5]:
# Attributes of 3-dimensional array
a3.shape,a3.size,a3.ndim,a3.dtype

((2, 3, 4), 24, 3, dtype('int32'))

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've create
import pandas as pd
arrayData=np.array([1,15,32,450])
dataOfarray=pd.DataFrame(arrayData,index=["First","second","third","forth"],columns=["Numbers"])
dataOfarray


Numbers
First         1
second       15
third        32
forth       450

In [7]:
# Create an array of shape (10, 2) with only ones
ones=np.ones(shape=(10,2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes=np.zeros(shape=(7,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3
newArray=np.arange(0,100,3)
newArray

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
newarray1=np.random.randint(0,10,size=(7,2))
newarray1

array([[9, 5],
       [5, 4],
       [5, 6],
       [3, 1],
       [7, 2],
       [6, 1],
       [3, 9]])

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
newArrayFloat=np.random.rand(3,5)
newArrayFloat


array([[0.04307187, 0.74208755, 0.24520125, 0.43088416, 0.10258424],
       [0.69964712, 0.49886501, 0.78342778, 0.56528347, 0.24653211],
       [0.62743456, 0.60944899, 0.37805808, 0.44037649, 0.68138898]])

In [33]:
# Set the random seed to 42
np.random.seed(0)
newArrraySeed=np.random.randint(0,10,size=(4,6))
newArrraySeed

# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [37]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
newrandomArray2=np.random.randint(1,10,size=(3,7))
newrandomArray2


# Find the unique numbers in the array you just created
np.unique(newrandomArray2)


array([1, 2, 3, 4, 5, 6, 8])

In [41]:
# Find the 0'th index of the latest array you create
newrandomArray2
newrandomArray2[0]

array([6, 1, 2, 3, 5, 3, 1])

In [43]:
# Get the first 2 rows of latest array you created
newrandomArray2[:2]

array([[6, 1, 2, 3, 5, 3, 1],
       [4, 3, 1, 8, 6, 1, 3]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
newrandomArray2[:2,:2]

array([[6, 1],
       [4, 3]])

In [54]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
newTestArray=np.random.randint(0,10,size=(3,5))
ones=np.ones((3,5))
newTestArray
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# Add the two arrays together

sumArrray=newTestArray+ones
sumArrray

array([[ 9.,  5.,  7.,  6.,  9.],
       [ 3.,  4., 10.,  8.,  6.],
       [ 4.,  5.,  6.,  4.,  4.]])

In [58]:
# Create another array of ones of shape (5, 3)
ones1=np.ones((5,3))
ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# Try add the array of ones and the other most recent array together
sumArray2=ones1+newTestArray
sumArray2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [62]:
# Create another array of ones of shape (3, 5)
ones2=np.ones((3,5))

In [64]:
# Subtract the new array of ones from the other most recent array
newTestArray
newTestArray-ones2

array([[7., 3., 5., 4., 7.],
       [1., 2., 8., 6., 4.],
       [2., 3., 4., 2., 2.]])

In [65]:
# Multiply the ones array with the latest array
newTestArray*ones2

array([[8., 4., 6., 5., 8.],
       [2., 3., 9., 7., 5.],
       [3., 4., 5., 3., 3.]])

In [66]:
# Take the latest array to the power of 2 us
newTestArray**2

array([[64, 16, 36, 25, 64],
       [ 4,  9, 81, 49, 25],
       [ 9, 16, 25,  9,  9]])

In [67]:
# Do the same thing with np.square()
np.square(newTestArray)

array([[64, 16, 36, 25, 64],
       [ 4,  9, 81, 49, 25],
       [ 9, 16, 25,  9,  9]])

In [68]:
# Find the mean of the latest array using np.mean()
np.mean(newTestArray)

5.0

In [71]:
# Find the maximum of the latest array using np.max()
newTestArray

np.max(newTestArray)

9

In [72]:
# Find the minimum of the latest array using np.min()
np.min(newTestArray)

2

In [73]:
# Find the standard deviation of the latest array
np.std(newTestArray)

2.0976176963403033

In [74]:
# Find the variance of the latest array
np.var(newTestArray)

4.4

In [77]:
# Reshape the latest array to (3, 5, 1)
newTestArray.reshape(3,5,1)


array([[[8],
        [4],
        [6],
        [5],
        [8]],

       [[2],
        [3],
        [9],
        [7],
        [5]],

       [[3],
        [4],
        [5],
        [3],
        [3]]])

In [83]:
# Transpose the latest array
arrayO=newTestArray.T
arrayO
arrayO.shape

(5, 3)

What does the transpose do?

In [84]:
# Create two arrays of random integers between 0 to 10
mat1=np.random.randint(0,10,size=(3,3))
mat2=np.random.randint(0,10,size=(3,2))
# one of size (3, 3) the other of size (3, 2)


In [85]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

array([[112,  76],
       [104,  76],
       [ 47,  35]])

In [86]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3=np.random.randint(0,10,size=(4,3))
mat4=np.random.randint(0,10,size=(4,3))


In [87]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3,mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [88]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(mat3.T,mat4)

array([[80, 64, 74],
       [77, 88, 88],
       [28,  7, 63]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [90]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to vari
test1=np.random.randint(0,10,size=(2,3))
test2=np.random.randint(0,10,size=(2,3))

In [93]:
# Compare the two arrays with '>'
test1
test2
test1>test2

array([[False, False, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [95]:
# Compare the two arrays with '>='
test1>=test2


array([[False, False, False],
       [ True, False, False]])

In [96]:
# Find which elements of the first array are greater than 7
test1>7

array([[False, False, False],
       [False, False, False]])

In [101]:
# Which parts of each array are equal? (try using '==')
test1==test2
test1

array([[2, 5, 5],
       [2, 5, 5]])

In [100]:
# Sort one of the arrays you just created in ascending order
np.sort(test1)

array([[2, 5, 5],
       [2, 5, 5]])

In [102]:
# Sort the indexes of one of the arrays you just created
np.argsort(test1)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [104]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(test1)

1

In [105]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(test1)

0

In [107]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(test1,axis=0)


array([0, 0, 0], dtype=int64)

In [109]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(test1,axis=1)

array([0, 0], dtype=int64)

In [110]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.92815918,  1.49072192,  0.19549934, -0.47160433,  1.81235465],
       [-2.29413748,  0.65120935, -1.13049645, -0.77734666,  1.11593845],
       [ 1.33945302, -1.76743365,  0.42441246,  1.08930905, -0.38418568]])

In [114]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.